name: Build BiohitPipettorPlus

on:
  push:
    branches: [ dev_advait ]
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  pull_request:
    branches: [ dev_advait ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x86'  #Force 32-bit Python


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry run pip install pyinstaller

    - name: Smoke test
      run: |
        poetry run pytest tests/ -v --tb=short

    - name: Build with PyInstaller
      run: |
        poetry run pyinstaller BiohitPipettorPlus.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BiohitPipettorPlus-Windows
        path: dist/BiohitPipettorPlus/

    - name: Zip the distribution
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        Compress-Archive -Path dist/BiohitPipettorPlus/* -DestinationPath BiohitPipettorPlus-Windows.zip

    - name: Create Release and Upload Files
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: BiohitPipettorPlus-Windows.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}